[workspace]
members = [
    'packages/raytracer-core',
    'packages/raytracer-cli',
    'packages/raytracer-benchmarks'
]

[profile.release]

[profile.bench]
lto = 'fat'
codegen-units = 1
incremental = false
opt-level = 3
debug = false